### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-Marinulis#2]
Muy buen trabajo!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 300 / 347
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

**Comment by Marinulis** [comment]
Buenos días Miguel. 
Muchas gracias por las correcciones. Acabo de subir un commit que las incluye. Respecto a las dos últimas, creo que ya estaban implementadas en la versión que subí el día de la evaluación o quizás es que no estoy entendiendo a qué te refieres:
1-El texto "Creando diversidad digital" está centrado en el contenedor flex ".main".
2-El header en versión móvil es un contenedor flex (".nav-header") en columna centrada que cuando pasa a tamaño tablet se transforma en una distribución en fila cuyos elementos se distribuyen hacia los extremos derecho e izquierdo.
Ya me dices si es correcto, ¡gracias!

**Comment by migueldelmazo** [comment]
Esto está para entrar a vivir señoría ! [https://media.giphy.com/media/8RxCFgu88jUbe/giphy.gif](https://media.giphy.com/media/8RxCFgu88jUbe/giphy.gif)
